### ISSUE TITLE
Example for coding a software 

### ISSUE THREAD

**Issue by hemangjoshi37a** [crewAIInc/crewAI-examples#129]
Please provide an example for coding a multiple file software

**Comment by JordanDest** [comment]
Game builder is a helpful example once you get it working. I think the docs might be OpenAI specific or otherwise outdated for the code_output argument. I agree though that more software related examples would be incredible, perhaps utilizing some of the newer features like custom managers and hierarchical sequences.

**Comment by hemangjoshi37a** [comment]
I use aider now with Claude sonet llm and it works great. Just sometimes it forgets after long conversation the working concept of the library but other than this it works great.
